@startuml
!define CiscoPuml https://raw.githubusercontent.com/Julien-cpsn/plantuml-cisco-icons/master
!include CiscoPuml/Icons/all.puml
!define CISCO_COLOR #006d99

Alice -> Bob : Test <$router,scale=0.75,color=CISCO_COLOR>

'listsprites

@enduml